import Head from "next/head";
import Jumbotron from "@/components/modules/Home/Jumbotron";
import RiderDriverContainer from "@/components/modules/Home/RiderDriverContainer";
import InstructionContainer from "@/components/modules/Home/InstructionContainer";
import DownloadCardContainer from "@/components/modules/Home/DownloadCardContainer";
import Footer from "@/components/common/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Jumbotron />
      <RiderDriverContainer />
      <InstructionContainer />
      <DownloadCardContainer />
      <Footer />
    </>
  );
}
